# This file compiled from .travis.yml.in

sudo: required

language: python

services:
  - docker

python:
  - "3.5.2"

env:
  - BASE_DOCKER_ON_TRAVIS=true

cache:
  pip: true
  directories:
    - node_modules
    - /home/travis/.rvm/gems

install:
  # Install NodeJS
  - nvm install 4.5.0

  # Install Python dependencies
  - python -m pip install --upgrade pip==8.1.1
  - python -m pip install -r requirements3.txt

  # Install Ruby
  - rvm install 2.3.1
  - rvm @global do gem install bundler -v 1.13.1
  - |
    bundler_uninstall=$( rvm @global do gem list ^bundler$ -i -v "!=1.13.1" )
    if [ "$bundler_uninstall" == "true" ]
    then
      rvm @global do gem uninstall bundler -v "!=1.13.1"
    fi
  - rvm use 2.3.1 --default

  # Install Docker
  - apt-cache madison docker-engine

  - docker version
  - sudo apt-get -o Dpkg::Options::="--force-confnew" install --yes --force-yes docker-engine=1.11.2-0~trusty

  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/1.8.0-rc1/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

  - docker version
  - docker-compose version

  # Invoke will get our other dependencies
  - invoke update_dependencies

script:
  - |
    invoke docker_machine_start
    sleep 60
  - nosetests
