name:       'TractDB'

brandimage: ''
brandtext:  'TractDB'

lessc: node_modules/.bin/lessc

navbar:
  items:
    - text: 'Login'
      link: 'login.html'
    - text: 'Status'
      link: 'status.html'

exclude:
  # Bootstrap
  - bootstrap/less
  # CSS/LESS files, these are all included by other less files and cannot compile on their own
  - css/styles.less
  - css/base/base_styles.less
  - css/base/base_variables.less
  - css/base/syntax.css
  - css/base/bar/base_bar.less
  - css/base/freelancer/base_freelancer.less
  - css/base/freelancer/freelancer.less
  - css/base/freelancer/mixins.less
  - css/base/freelancer/variables.less
  # Node
  - node_modules
  - npm-shrinkwrap.json
  - package.json
  # Python
  - env35
  - requirements3.in
  - requirements3.txt
  - tasks.py
  - tasks.pyc
  # README
  - README.md
  # Ruby
  - Gemfile
  - Gemfile.lock
  # Tests
  - tests
