baseurl:    ''

tractdb:
  baseurl_pyramid: http://{{ DOCKER_LOCALIZE_IP }}:8080

  configure:
    url_fitbit: https://fitbit.com/oauth2/authorize?response_type=code&client_id=228RY9&redirect_uri=https%3A%2F%2Ftractdb.org%2Fconfigure%2Ffitbit%2Fcallback&scope=activity%20heartrate%20location%20nutrition%20profile%20settings%20sleep%20social%20weight
